name: Build and test
on:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16', '1.17', '1.18', '1.19', '1.20' ]
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for new-from-rev option in .golangci.yml
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: |
          cd codec
          go test
          a=( "" "safe" "codecgen" "notfastpath" "codecgen notfastpath" "codecgen safe" "safe notfastpath" )
          for i in "${a[@]}"; do echo ">>>> TAGS: $i"; go test "-tags=alltests $i" -run=Suite; done
